### ISSUE TITLE
Cannot use Blazored ILocalStorageService inside ViewModel

### ISSUE THREAD

**Issue by SSchulze1989** [klemmchr/MvvmBlazor#102] opened 2022-04-30 20:12 UTC
### Bug description

When injecting an instance of Blazored `ILocalStorageService` into a ViewModel and inheriting from `MvvmComponentBase<>`, trying to access a value through the local store will throw the following exception:
```diff
- JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
```

This is normally happening when the page is prerendered, however this exception is still being thrown when called inside `OnAfterRenderedAsync()` and also when prerendering is enabled.

I tried the same approach but injected the ViewModel directly into the component and it was working fine.

### Expectation

There should be no Exception when the page is not being rendered or when localStorage is accessed after `OnAfterRendered()`

### Code sample

```C#
public class MyViewModel : ViewModelBase
    {
        private readonly ILocalStorageService localStorage;

        public MyViewModel(ILocalStorageService localStorage)
        {
            this.localStorage = localStorage;
        }

        public override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
                await localStorage.GetItemAsStringAsync("test");
        }
    }
```

### Version

6.0.3

### Are you using Blazor WASM or Blazor Server?

Blazor Server

### What operation system are you working with?

Windows

**Comment by klemmchr** [comment] 2022-05-01 16:11
Please have a look at [this comment](https://github.com/klemmchr/MvvmBlazor/issues/98#issuecomment-1106555803) which explains the issue and how to avoid it.

Duplicate of #98

**Closed by klemmchr** 2022-05-01 16:11 UTC
Labels: type: bug, status: triage

**Comment by SSchulze1989** [comment] 2022-05-05 15:58
Thx. So i ended up injecting the viewmodel directly - as in your example on the main page - and it works like a charm.
Awesome!
